# ==== DATABASE CONSTANTS ====


DB_COMPUTER_TYPE_NAME = "COMPUTER"
DB_DEVICE_TYPE_NAME = "DEVICE"
DB_USER_TYPE_NAME = "USER"
DB_PROGRAM_TYPE_NAME = "PROGRAM"
DB_TIP_TYPE_NAME = "TIP"
DB_NAME = "database.db"
DB_TABLE_NAME = "program_data"
DB_TYPE_NAME_LIST = ("", "Użytkownicy", "Komputery", "Urządzenia", "Programy", "Wskazówki")
DB_TYPE_VALUE_LIST = (DB_USER_TYPE_NAME, DB_COMPUTER_TYPE_NAME, DB_DEVICE_TYPE_NAME, DB_PROGRAM_TYPE_NAME, DB_TIP_TYPE_NAME)


# ==== INTERFACE ====

# ==== MAIN WINDOW

# ---- FRAMES ----

BOTTOM_FRAME_HEIGHT = 30
BOTTOM_FRAME_BG_COLOR = "Gray53"
LEFT_FRAME_WIDTH = 386
MAIN_WINDOW_SIZE = "1366x768"
TOP_FRAME_HEIGHT = 30
TOP_FRAME_BG_COLOR = "Gray53"

# --- WIDGETS ---

BUTTON_BG_COLOR = "Gray74"
BUTTON_FG_COLOR = "Gray26"
CURRENT_USER_LABEL_NAME = "Aktywny użytkownik: "
PLK_ADD_ITEM_BUTTON_NAME = "Dodaj"
PLK_USER_MEMO_WIDTH = 20
PLK_USER_MEMO_HEIGHT = 47
PLK_USER_MEMO_BG_COLOR = "Gray23"
PLK_USER_MEMO_FG_COLOR = "Gray97"
PLK_USER_MEMO_FONT = ("century gothic", 12)
SEARCH_LABEL_TEXT = "Szukaj "
SEARCH_ENTRY_WIIDTH = 46
TREE_STYLE_COLUMN_WIDTH = 80
TREE_STYLE_COLUMN_MINWIDTH = 5
TREE_STYLE_BD = 2
TREE_STYLE_BG_COLOR = "Gray34"
TREE_STYLE_BG_DATA_COLOR = "Gray50"
TREE_STYLE_FG_COLOR = "White"
TREE_STYLE_HEIGHT = 47
TREE_STYLE_FONT = ("verdana", 8)

# ==== ADD ITEM

ADD_DESCRIPTION_NAME = "Opis"
ADD_DESCRIPTION_WIDTH = 30
ADD_ITEM_BUTTON_NAME = "Dodaj"
CANCEL_BUTTON_NAME = "Anuluj"
ADD_ITEM_WINDOW_SIZE = "300x400"
ADD_ITEM_WINDOW_TITLE = "Dodaj do bazy danych"
ADD_NAME_LABEL_TEXT = "Nazwa"
ADD_NAME_TEXT_WIDTH = 16
ADD_NAME_TEXT_HEIGHT = 1

# ==== MEMO COLORS

MEMO_TAG_INFO_FOREGROUND_COLOR = "gold2"
MEMO_TAG_COMPUTER_NAME_FOREGROUND_COLOR = "SkyBlue2"
MEMO_TAG_EMAIL_COLOR = "LightSkyBlue1"
MEMO_TAG_EMILKA_APPLICATION_COLOR = "coral2"
MEMO_TAG_PLK_NUMBER_FOREGROUND_COLOR = "light steel blue"
MEMO_TAG_DATE_FOREGROUND_COLOR = "light goldenrod"
MEMO_TAG_HASHTAG_FOREGROUND_COLOR = "LightCyan3"
MEMO_TAG_WEBPAGE_COLOR = MEMO_TAG_EMAIL_COLOR

MEMO_TAG_SEARCH_STRING_BACKGROUND_COLOR = PLK_USER_MEMO_FG_COLOR
MEMO_TAG_SEARCH_STRING_FOREGROUND_COLOR = PLK_USER_MEMO_BG_COLOR

# ==== MEMO STRINGS

ADD_ITEM_INFO = "================== UTWORZONO: "
CHANGE_DESCRIPTION_INFO = "================== ZMIENIONO OPIS: "
CHANGE_NAME_INFO = "================== ZMIENIONO NAZWĘ: "
CHANGE_TYPE_INFO = "================== ZMIENIONO TYP: "

# ==== MEMO_TAG_NAMES

MEMO_TAG_DATE = "memo_date"
MEMO_TAG_EMAIL = "email_address"
MEMO_TAG_EMILKA_APPLICATION = "emilka_application"
MEMO_TAG_INFO = "memo_info"
MEMO_TAG_HASHTAG = "memo_hashtag"
MEMO_TAG_PLK_NUMBER = "memo_plk_number"
MEMO_TAG_COMPUTER_NAME = "memo_computer_number"
MEMO_TAG_SEARCH_STRING = "memo_search_string"
MEMO_TAG_WEBPAGE = "webpage"

# === SEARCH ENTRY

COMMAND_PREFIX = "COM:"

# === REGULAR EXPRESSIONS

REG_DATES = r"\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d"
REG_ADD_ITEM_INFO = ADD_ITEM_INFO + ".*"
REG_CHANGE_DESCRIPTION_INFO = CHANGE_DESCRIPTION_INFO + ".*"
REG_CHANGE_NAME_INFO = CHANGE_NAME_INFO + ".*"
REG_CHANGE_TYPE_INFO = CHANGE_TYPE_INFO + ".*"
REG_HASHTAG = r"(?:\s|^)#[A-Za-z0-9\-\.\_]+(?:\s|$)"
REG_PLK_NUMBER = r"PLK\d\d\d\d\d\d"
REG_COMPUTER_NUMBER = r"\[(.*?)\]"
REG_EMILKA_APPLICATION = r"ZGL\d\d\d\d\d\d"
REG_EMAIL = r'\S+@\S+'
REG_WEBPAGE = "TEMP_REGEX"


# ==== OTHER

PASS_PREFIX = "iziu#"
